config/routes.rb
Funpachin::Application.routes.draw do
  root :to => 'toppage#index'

  match '/auth/:provider/callback' => 'sessions#callback'
  match '/auth/failure' => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout

  scope '/admin' do
    match '/', :controller => :admin, :action => :index

    resources :news_feeds
    resources :members
    resources :account_managers
  end
  

end

app/models/account_manager.rb
class AccountManager < ActiveRecord::Base
  attr_accessible :screen_name

  def self.allow_users?(name)
    !AccountManager.find_by_screen_name(name).try(:screen_name).nil?
  end
end

app/controllers/account_managers_controller.rb
class AccountManagersController < AdminController
  # GET /account_managers
  # GET /account_managers.json
  def index
    @account_managers = AccountManager.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /account_managers/1
  # GET /account_managers/1.json
  def show
    @account_manager = AccountManager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /account_managers/new
  # GET /account_managers/new.json
  def new
    @account_manager = AccountManager.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /account_managers/1/edit
  def edit
    @account_manager = AccountManager.find(params[:id])
  end

  # POST /account_managers
  # POST /account_managers.json
  def create
    @account_manager = AccountManager.new(params[:account_manager])

    respond_to do |format|
      if @account_manager.save
        format.html { redirect_to @account_manager, notice: 'Account manager was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /account_managers/1
  # PUT /account_managers/1.json
  def update
    @account_manager = AccountManager.find(params[:id])

    respond_to do |format|
      if @account_manager.update_attributes(params[:account_manager])
        format.html { redirect_to @account_manager, notice: 'Account manager was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /account_managers/1
  # DELETE /account_managers/1.json
  def destroy
    @account_manager = AccountManager.find(params[:id])
    @account_manager.destroy

    respond_to do |format|
      format.html { redirect_to account_managers_url }
    end
  end
end

app/helpers/account_managers_helper.rb
module AccountManagersHelper
end

app/views/account_managers/_form.html.haml
= form_for @account_manager, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :screen_name, :class => 'control-label'
    .controls
      = f.text_area :screen_name, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), account_managers_path, :class => 'btn'

app/views/account_managers/edit.html.haml
- model_class = @account_manager.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/account_managers/index.html.haml
- model_class = AccountManager.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:screen_name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @account_managers.each do |account_manager|
      %tr
        %td= link_to account_manager.id, account_manager_path(account_manager)
        %td= account_manager.screen_name
        %td=l account_manager.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_account_manager_path(account_manager), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), account_manager_path(account_manager), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_account_manager_path, :class => 'btn btn-primary'

app/views/account_managers/new.html.haml
- model_class = @account_manager.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/account_managers/show.html.haml
- model_class = @account_manager.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:screen_name) + ':'
  %br
  = @account_manager.screen_name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), account_managers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_account_manager_path(@account_manager), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), account_manager_path(@account_manager), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'