config/routes.rb
Funpachin::Application.routes.draw do
  root :to => 'toppage#index'

  match '/auth/:provider/callback' => 'sessions#callback'
  match '/auth/failure' => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout

  scope '/admin' do
    match '/', :controller => :admin, :action => :index

    resources :news_feeds
    resources :members
    resources :account_managers
  end
  

end

app/models/news_feed.rb
class NewsFeed < ActiveRecord::Base
  attr_accessible :description
end

app/controllers/news_feeds_controller.rb
class NewsFeedsController < AdminController
  # GET /news_feeds
  # GET /news_feeds.json
  def index
    @news_feeds = NewsFeed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news_feeds }
    end
  end

  # GET /news_feeds/1
  # GET /news_feeds/1.json
  def show
    @news_feed = NewsFeed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news_feed }
    end
  end

  # GET /news_feeds/new
  # GET /news_feeds/new.json
  def new
    @news_feed = NewsFeed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news_feed }
    end
  end

  # GET /news_feeds/1/edit
  def edit
    @news_feed = NewsFeed.find(params[:id])
  end

  # POST /news_feeds
  # POST /news_feeds.json
  def create
    @news_feed = NewsFeed.new(params[:news_feed])

    respond_to do |format|
      if @news_feed.save
        format.html { redirect_to @news_feed, notice: 'News feed was successfully created.' }
        format.json { render json: @news_feed, status: :created, location: @news_feed }
      else
        format.html { render action: "new" }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news_feeds/1
  # PUT /news_feeds/1.json
  def update
    @news_feed = NewsFeed.find(params[:id])

    respond_to do |format|
      if @news_feed.update_attributes(params[:news_feed])
        format.html { redirect_to @news_feed, notice: 'News feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_feeds/1
  # DELETE /news_feeds/1.json
  def destroy
    @news_feed = NewsFeed.find(params[:id])
    @news_feed.destroy

    respond_to do |format|
      format.html { redirect_to news_feeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/news_feeds_helper.rb
module NewsFeedsHelper
end

app/views/news_feeds/_form.html.haml
= form_for @news_feed, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_field span5'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), news_feeds_path, :class => 'btn'

app/views/news_feeds/edit.html.haml
- model_class = @news_feed.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/news_feeds/index.html.haml
- model_class = NewsFeed.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @news_feeds.each do |news_feed|
      %tr
        %td= link_to news_feed.id, news_feed_path(news_feed)
        %td= news_feed.description
        %td=l news_feed.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_news_feed_path(news_feed), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), news_feed_path(news_feed), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_news_feed_path, :class => 'btn btn-primary'

app/views/news_feeds/new.html.haml
- model_class = @news_feed.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/news_feeds/show.html.haml
- model_class = @news_feed.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @news_feed.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), news_feeds_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_news_feed_path(@news_feed), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), news_feed_path(@news_feed), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'