config/routes.rb
Funpachin::Application.routes.draw do
  root :to => 'toppage#index'

  match '/auth/:provider/callback' => 'sessions#callback'
  match '/auth/failure' => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout

  scope '/admin' do
    match '/', :controller => :admin, :action => :index

    resources :news_feeds
    resources :members
    resources :account_managers
  end
  

end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :status
  attr_accessible :name, :other, :twitter, :status_id

  before_validation do
    self.name = self.name.strip
  end

  before_validation do
    self.twitter = self.twitter.strip
  end
end

app/controllers/members_controller.rb
class MembersController < AdminController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all
    @status = Status.hashall

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.haml
= form_for @member, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :status_id, :class => 'control-label'
    .controls
      %select(class="number_field" id="member_status_id" name="member[status_id]" type="number") 
        = options_from_collection_for_select(Status.all, :id, :detail, @member.status_id)
  .control-group
    = f.label :twitter, :class => 'control-label'
    .controls
      = f.text_field :twitter, :class => 'text_field'
  .control-group
    = f.label :other, :class => 'control-label'
    .controls
      = f.text_area :other, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), members_path, :class => 'btn'

app/views/members/edit.html.haml
- model_class = @member.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/members/index.html.haml
- model_class = Member.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:status_id)
      %th= model_class.human_attribute_name(:twitter)
      %th= model_class.human_attribute_name(:other)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @members.each do |member|
      %tr
        %td= link_to member.id, member_path(member)
        %td= member.name
        %td= @status[member.status_id]
        %td= member.twitter
        %td= member.other
        %td=l member.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_member_path(member), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), member_path(member), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_member_path, :class => 'btn btn-primary'

app/views/members/new.html.haml
- model_class = @member.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/members/show.html.haml
- model_class = @member.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @member.name
%p
  %strong= model_class.human_attribute_name(:status_id) + ':'
  %br
  = Status.hashall[@member.status_id]
%p
  %strong= model_class.human_attribute_name(:twitter) + ':'
  %br
  = @member.twitter
%p
  %strong= model_class.human_attribute_name(:other) + ':'
  %br
  = @member.other

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), members_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_member_path(@member), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), member_path(@member), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'